version: '3.8'
services:
  db:
    image: postgres:13
    container_name: poc-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: mcp-poc-app
    depends_on:
      - db
    environment:
      DB_NAME:       ${DB_NAME}
      DB_USER:       ${DB_USER}
      DB_PASSWORD:   ${DB_PASSWORD}
      DB_HOST:       db
      DB_PORT:       5432
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      GCP_PROJECT:   ${GCP_PROJECT}
    ports:
      - "8000:8000"
    command: ["python", "server.py"]

volumes:
  db_data:
